GRANT ALL PRIVILEGES ON *.* TO 'hr.admin'@'192.168.0.0/255.255.255.0' IDENTIFIED BY 'maria105sql' WITH GRANT OPTION;
USE hr;
SHOW TABLES;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE regions  ;
SET FOREIGN_KEY_CHECKS = 1; -- Enable foreign key checks